"""
Django settings for lab8 project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path


# Ruta principal del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuración de seguridad
SECRET_KEY = (
    'django-insecure-'
    'yx$nrcutq*)sxl6o69hsmw0g50b4hpxtra='
    ')xu_9*33en(u9cd'
)

DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]


# Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'oauth2_provider',
    'corsheaders',

    'pokedex',
    'api',
]


# Middleware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'oauth2_provider.middleware.OAuth2TokenMiddleware',
]


ROOT_URLCONF = 'lab8.urls'


# Configuración de plantillas
TEMPLATES = [
    {
        'BACKEND': (
            'django.template.backends.django.'
            'DjangoTemplates'
        ),
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                (
                    'django.template.context_processors.'
                    'debug'
                ),
                (
                    'django.template.context_processors.'
                    'request'
                ),
                (
                    'django.contrib.auth.context_processors.'
                    'auth'
                ),
                (
                    'django.contrib.messages.'
                    'context_processors.messages'
                ),
            ],
        },
    },
]


WSGI_APPLICATION = 'lab8.wsgi.application'


# Base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Validación de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# Idioma y zona horaria
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Archivos estáticos
STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Archivos multimedia
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Tipo de clave primaria
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Redirecciones de autenticación
LOGIN_REDIRECT_URL = 'pokedex:index'

LOGIN_URL = 'pokedex:login'

LOGOUT_REDIRECT_URL = 'pokedex:index'


# Configuración de OAuth
OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': (
        'oauth2_provider.oauth2_backends.'
        'OAuthLibCore'
    ),
    'ACCESS_TOKEN_EXPIRE_SECONDS': 2592000,
}


AUTHENTICATION_BACKENDS = (
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
)


# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# Direcciones permitidas para React
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',

    'http://localhost:3000',
    'http://127.0.0.1:3000',

    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
